[package]
name = "edn-rs"
version = "0.11.0"
authors = ["Julia Naomi <jnboeira@outlook.com>",  "Otavio Pace <otaviopp8@gmail.com>"]
description = "Crate to parse and emit EDN"
readme = "README.md"
documentation = "https://docs.rs/edn-rs/"
repository = "https://github.com/naomijub/edn-rs"
keywords = ["EDN"]
license = "LGPL-3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
async = ["futures"]

[dependencies]
regex = "1"
futures = {version = "0.3.5", optional = true }

[dev-dependencies]
tokio = {version = "0.2.22", features = ["macros"] }


[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[[example]]
name = "async"
required-features = ["async"]