[package]
name = "edn-rs"
version = "0.10.2"
authors = ["Julia Naomi <jnboeira@outlook.com>",  "Otavio Pace <otaviopp8@gmail.com>"]
description = "Crate to parse and emit EDN"
readme = "README.md"
documentation = "https://docs.rs/edn-rs/"
repository = "https://github.com/naomijub/edn-rs"
keywords = ["EDN"]
license = "LGPL-3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
