name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Examples
      run: |
        cargo run --example json_to_edn
        cargo run --example navigate_edn
        cargo run --example parse_str
        cargo run --example serialize
        cargo run --example tokenize_edn
        cargo run --example iterator
        cargo run --example to_vec
        cargo run --example async --features "async"
    - name: FMT
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
